# -*- mode: ruby -*-
# vim: set ft=ruby :

machines = {
  :"zabbix-server" => {
    :box_name => "centos/7",
    :ip_addr => '192.168.11.150',
    :v_name => 'zabbix-server',
    :v_memory => '2048',
    :v_cpus => '2'
  },
  :"zabbix-agent" => {
    :box_name => "centos/7",
    :ip_addr => '192.168.11.160',
    :v_name => 'zabbix-agent',
    :v_memory => '2048',
    :v_cpus => '2'
  }
}

Vagrant.configure("2") do |config|
  config.vm.synced_folder ".", "/vagrant", disabled: true
  machines.each do |boxname, boxconfig|
    config.vm.define boxname do |box|
      box.vm.box = boxconfig[:box_name]
      box.vm.host_name = boxname.to_s
      box.vm.network "private_network", ip: boxconfig[:ip_addr]
      box.vm.provider :virtualbox do |v|
        v.memory = boxconfig[:v_memory]
        v.cpus = boxconfig[:v_cpus]
        v.name = boxconfig[:v_name]
      end
      box.vm.provision "shell", inline: <<-SHELL
        mkdir -p ~root/.ssh; cp ~vagrant/.ssh/auth* ~root/.ssh
        sed -i '65s/PasswordAuthentication no/PasswordAuthentication yes/g' /etc/ssh/sshd_config
        systemctl restart sshd
      SHELL
    end
  end
end
